name: mvr
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/charlie9830

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.6.1
  collection: ^1.19.1
  flutter:
    sdk: flutter
  path: ^1.9.1
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

